version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: demo_trivia
        restart: unless-stopped
        ports:
            - "9000:9000"
        volumes:
            - ./:/var/www
        working_dir: /var/www
        networks:
            - demo_trivia_network
        depends_on:
            - database

    nginx:
        image: nginx:alpine
        container_name: demo_trivia_nginx
        restart: unless-stopped
        ports:
            - "8081:80"
        volumes:
            - ./:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - demo_trivia_network

    database:
        image: mysql:8.0
        container_name: demo_trivia_mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_DATABASE: "${DB_DATABASE}"
        volumes:
            - demo_db_vol:/var/lib/mysql
            - ./my.cnf:/etc/mysql/my.cnf
        networks:
            - demo_trivia_network
        ports:
            - "3306:3306"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: demo_trivia_phpmyadmin
        restart: always
        environment:
            PMA_HOST: database
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        ports:
            - "8080:80"
        depends_on:
            - database
        networks:
            - demo_trivia_network

networks:
    demo_trivia_network:
        driver: bridge
volumes:
    demo_db_vol:
        driver: local
